$ErrorActionPreference = 'Stop'

$modelsPath = Join-Path $PSScriptRoot 'models'
$files = @(Get-ChildItem -LiteralPath $modelsPath -File -Recurse |
    Where-Object { $_.Extension -ieq '.obj' } |
    Sort-Object FullName)

$entries = @(
    foreach ($file in $files) {
        if ($file.Length -gt 10MB) {
            throw "Model exceeds the 10 MB limit: $($file.FullName)"
        }
        [ordered]@{
            name = $file.FullName.Substring($modelsPath.Length + 1).Replace('\', '/')
            path = 'models/' + (($file.FullName.Substring($modelsPath.Length + 1).Split('\') |
                ForEach-Object { [System.Uri]::EscapeDataString($_) }) -join '/')
        }
    }
)

# Store URL paths only; geometry is loaded on demand by the browser.
$json = ConvertTo-Json -InputObject $entries -Depth 3
$content = "// Generated by update-models.ps1. Edit the .obj files, not this file.`nwindow.GLYPH_MODELS = $json;`n"
$manifestPath = Join-Path $modelsPath 'manifest.js'
[System.IO.File]::WriteAllText($manifestPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "Updated models\manifest.js with $($files.Count) model(s). Reload GLYPH to see the updated list."
