// Generated by update-models.ps1. Edit the .obj files, not this file.
window.GLYPH_MODELS = [
    {
        "name":  "torus-knot.obj",
        "path":  "models/torus-knot.obj"
    },
    {
        "name":  "torus.obj",
        "path":  "models/torus.obj"
    },
    {
        "name":  "cube.obj",
        "path":  "models/cube.obj"
    },
    {
        "name":  "octahedron.obj",
        "path":  "models/octahedron.obj"
    },
    {
        "name":  "lucky_cat.obj",
        "path":  "models/lucky_cat.obj"
    },
    {
        "name":  "adventurer_boy.obj",
        "path":  "models/adventurer_boy.obj"
    }
];
